
customer_query:
  description: >
    My account login is not recognising email address.
  expected_output: >
    Your final answer must include a solution that helps the system recognise the email address.
evaluate_customer_interaction:
    assigned_agent: evaluation_agent
    description: Evaluates the quality of the response given by the crew in the most relevant way.
    expected_output: Provide a detailed explanation of whether the response from the customer service agent is sufficient. Suggest improvements if necessary. Output should be a JSON in the with keys approved (binary value) and feedback.
